### PR TITLE
Update to crossfire.cpp

### PR DESCRIPTION
**Pull request by stefan73**
Add support for 250mW @ CF micro. Before using 250mW resultet in 0mW in the telemetry sensors.

### CODE REVIEW

**Comment by qba667** [comment]
Items on the list should be ordered, but merging anyhow.

**Comment by stefan73** [comment]
Thanks for merging. FYI: pls do not order entries. You do not get the Milliwatts from the CF module but the ID of the transmit power. CF introduced 250mW after the inital definition of transmit powers. This is why the 250mW is last in the array.

**Comment by qba667** [comment]
I just debug it, and seen this strange indexing - thanks!

**Comment by qba667** [comment]
Btw, please join to our chat channel on:
https://chat.open-tx.org/channel/nv14

**Pull request merged**
